server:
  port: 8084
# eureka-clienté…ç½®
eureka:
  client:
    service-url:
      default-zone: http://106.14.144.168:8761/eureka/
  instance:
    ip-address: 106.14.144.168
    prefer-ip-address: true